from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from io import BytesIO
from datetime import datetime
import re

def generate_professional_pdf(analysis, summary, model, timestamp):
    """Generate a professionally formatted PDF with proper spacing, titles, and sections"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )
    
    # Define professional styles
    styles = getSampleStyleSheet()
    story = []
    
    # Custom Styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=28,
        textColor=colors.HexColor('#14b8a6'),
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=14,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    heading1_style = ParagraphStyle(
        'CustomHeading1',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#0f766e'),
        spaceAfter=12,
        spaceBefore=16,
        fontName='Helvetica-Bold',
        borderPadding=5,
        backColor=colors.HexColor('#f0fdfa')
    )
    
    heading2_style = ParagraphStyle(
        'CustomHeading2',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#14b8a6'),
        spaceAfter=8,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=8,
        alignment=TA_JUSTIFY,
        leading=16
    )
    
    bullet_style = ParagraphStyle(
        'CustomBullet',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6,
        leftIndent=20,
        bulletIndent=10,
        leading=14
    )
    
    # ===== COVER PAGE =====
    story.append(Spacer(1, 1.5*inch))
    story.append(Paragraph('🎯 AI Resume Analysis Report', title_style))
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph('Professional ATS & Career Insights', subtitle_style))
    story.append(Spacer(1, 0.5*inch))
    
    # Metadata table
    meta_data = [
        ['AI Model:', model],
        ['Generated:', timestamp.strftime('%B %d, %Y')],
        ['Time:', timestamp.strftime('%I:%M %p')]
    ]
    
    meta_table = Table(meta_data, colWidths=[2*inch, 3*inch])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0fdfa')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#1e293b')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#14b8a6')),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
        ('PADDING', (0, 0), (-1, -1), 12),
    ]))
    
    story.append(meta_table)
    story.append(Spacer(1, 0.5*inch))
    
    disclaimer_text = """
    <b>Confidential Document</b><br/>
    This analysis is generated by AI and should be used as a decision-support tool only. 
    Always combine with human judgment and verify findings through interviews.
    """
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#64748b'),
        alignment=TA_CENTER,
        leading=12
    )
    story.append(Paragraph(disclaimer_text, disclaimer_style))
    
    # Page break after cover
    story.append(PageBreak())
    
    # ===== MAIN CONTENT =====
    story.append(Paragraph('📊 Detailed Analysis Report', heading1_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Parse and format the analysis content
    lines = analysis.split('\n')
    
    for line in lines:
        line = line.strip()
        
        if not line:
            story.append(Spacer(1, 8))
            continue
        
        # Detect headings with ## or #
        if line.startswith('##'):
            heading_text = line.replace('##', '').strip()
            heading_text = re.sub(r'[#*_]', '', heading_text)  # Remove markdown symbols
            story.append(Spacer(1, 12))
            story.append(Paragraph(heading_text, heading2_style))
            
        elif line.startswith('#'):
            heading_text = line.replace('#', '').strip()
            heading_text = re.sub(r'[#*_]', '', heading_text)
            story.append(Spacer(1, 16))
            story.append(Paragraph(heading_text, heading1_style))
            
        # Detect bullet points
        elif line.startswith('-') or line.startswith('•') or line.startswith('*'):
            bullet_text = line.lstrip('-•* ').strip()
            # Clean markdown
            bullet_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', bullet_text)
            bullet_text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', bullet_text)
            story.append(Paragraph(f'• {bullet_text}', bullet_style))
            
        # Regular paragraph
        else:
            # Clean and format markdown
            text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
            text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
            text = re.sub(r'`(.*?)`', r'<font face="Courier"><b>\1</b></font>', text)
            
            # Skip very short lines that might be artifacts
            if len(text) > 3:
                story.append(Paragraph(text, body_style))
    
    # ===== THANK YOU PAGE =====
    story.append(PageBreak())
    story.append(Spacer(1, 2*inch))
    
    thank_you_title = ParagraphStyle(
        'ThankYouTitle',
        parent=styles['Heading1'],
        fontSize=32,
        textColor=colors.HexColor('#14b8a6'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    thank_you_text = ParagraphStyle(
        'ThankYouText',
        parent=styles['Normal'],
        fontSize=14,
        textColor=colors.HexColor('#334155'),
        spaceAfter=12,
        alignment=TA_CENTER,
        leading=20
    )
    
    story.append(Paragraph('🎉 Thank You!', thank_you_title))
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph('Your resume analysis is complete.', thank_you_text))
    story.append(Spacer(1, 0.2*inch))
    story.append(Paragraph('We hope this analysis helps you land your dream job!', thank_you_text))
    story.append(Spacer(1, 0.3*inch))
    
    success_message = """
    <b>Best of luck with your application! 🚀</b><br/><br/>
    <i>Powered by AI • Resume screening made intelligent</i>
    """
    story.append(Paragraph(success_message, thank_you_text))
    
    # Build PDF
    try:
        doc.build(story)
        buffer.seek(0)
        return buffer
    except Exception as e:
        print(f"PDF Generation Error: {e}")
        # Return simple fallback PDF
        buffer = BytesIO()
        simple_doc = SimpleDocTemplate(buffer, pagesize=letter)
        error_story = [
            Paragraph(f'PDF Generation Error', styles['Title']),
            Spacer(1, 0.2*inch),
            Paragraph(f'Error: {str(e)}', styles['Normal']),
            Spacer(1, 0.2*inch),
            Paragraph('Please try downloading as TXT or MD format.', styles['Normal'])
        ]
        simple_doc.build(error_story)
        buffer.seek(0)
        return buffer


